packages:
  - "apps/*"
  - "tools/*"
  - "packages/*"

catalog:
  "typescript": "5.8.2"
  "@types/bun": "^1.2.10"
  "better-auth": "^1.2.7"
  "superjson": "^2.2.2"
  "zod": "^3.24.3"
  "@t3-oss/env-core": "^0.12.0"
  "drizzle-orm": "beta"

catalogs:
  react:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "^19.1.2"
    "@types/react-dom": "^19.1.2"
  trpc:
    "@trpc/server": "^11.1.0"
    "@trpc/client": "^11.1.0"
    "@trpc/tanstack-react-query": "^11.1.0"
  tailwind:
    "tailwindcss": "^4.1.4"
    "@tailwindcss/postcss": "^4.1.4"
    "@tailwindcss/vite": "^4.1.4"
    "postcss": "^8.5.3"
    "tw-animate-css": "^1.2.5"
    "class-variance-authority": "^0.7.1"
    "clsx": "^2.1.1"
    "tailwind-merge": "^3.2.0"